---
- name: set hostname
  hostname: name={{ base_host_name }}

- name: install necessary base packages
  apt: name={{ item }} state=latest update_cache=true
  with_items:
    - tmux
    - git
    - vim
    - zsh
    - build-essential
    - curl
    - wget
    - postfix
    - python-software-properties

- include: dotfiles.yml
